"""
SBD Demand Forecast MCP Server
================================
This is the MCP server you built at Stanley Black and Decker.
It gives Claude structured, safe access to your forecast data.

Run with:  uvicorn sprint5_mcp_server:app --reload --port 8000
Test at:   http://localhost:8000/docs
"""

import os
import pandas as pd
import numpy as np
from fastapi import FastAPI, HTTPException
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

# Create the FastAPI application
# This is the main object that holds all your tools
app = FastAPI(
    title="SBD Demand Forecast MCP Server",
    description="Gives Claude safe access to SBD forecast and inventory data",
    version="1.0.0"
)

print("Loading SBD data...")

# Load your sales data
df = pd.read_csv('data/sbd_sales_data.csv')
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['sku_id','warehouse','date']).reset_index(drop=True)

# # Calculate summary — same as Sprint 4
# summary = df.groupby(['sku_id','warehouse']).agg(
#     avg_demand=('demand','mean'),
#     last_inventory=('inventory','last'),
# ).reset_index()

# summary['weeks_of_supply'] = (
#     summary['last_inventory'] / summary['avg_demand']
# ).round(1)

# summary['risk'] = summary['weeks_of_supply'].apply(
#     lambda x: 'HIGH' if x < 16 else 'MEDIUM' if x < 20 else 'LOW'
# )


# Load XGBoost forecast predictions
# Generated by generate_forecasts.py
xgb_forecast_path = 'data/xgboost_forecasts.csv'

if os.path.exists(xgb_forecast_path):
    summary = pd.read_csv(xgb_forecast_path)
    summary = summary.rename(columns={
        'avg_weekly_forecast': 'avg_demand'
    })
    print("Using XGBoost model predictions")
else:
    print("XGBoost forecasts not found — falling back to simple averages")
    summary = df.groupby(['sku_id','warehouse']).agg(
        avg_demand=('demand','mean'),
        last_inventory=('inventory','last'),
    ).reset_index()
    summary['weeks_of_supply'] = (
        summary['last_inventory'] / summary['avg_demand']
    ).round(1)
    summary['risk'] = summary['weeks_of_supply'].apply(
        lambda x: 'HIGH' if x < 16 else 'MEDIUM' if x < 20 else 'LOW'
    )

print(f"Data loaded — {len(summary)} SKU/warehouse combinations ready")
print(f"Warehouses: {df['warehouse'].unique().tolist()}")
print(f"Total SKUs: {df['sku_id'].nunique()}")



# ─────────────────────────────────────────
# TOOL 1 — get_stockout_risk
# ─────────────────────────────────────────

@app.get("/tools/get_stockout_risk")
def get_stockout_risk(
    warehouse: Optional[str] = None,
    weeks_ahead: int = 2,
    top_n: int = 10
):
    """
    Returns top N SKUs at highest stockout risk.
    This is the most used tool — planners call this every Monday morning.
    
    Parameters:
        warehouse: filter to one warehouse (optional)
        weeks_ahead: how many weeks to look ahead (1-4)
        top_n: how many SKUs to return
    """
    
    # Start with full summary
    result = summary.copy()
    
    # Filter by warehouse if provided
    if warehouse:
        result = result[
            result['warehouse'].str.lower() == warehouse.lower()
        ]
        
        # If warehouse not found return clear error
        if result.empty:
            raise HTTPException(
                status_code=404,
                detail=f"Warehouse '{warehouse}' not found. Available: Atlanta, Chicago, Dallas, Newark"
            )
    
    # Sort by risk — lowest weeks of supply first = most urgent first
    result = result.sort_values('weeks_of_supply', ascending=True)
    
    # Take top N
    result = result.head(top_n)
    
    # Build clean response
    items = []
    for _, row in result.iterrows():
        items.append({
            "sku_id": row['sku_id'],
            "warehouse": row['warehouse'],
            "risk_level": row['risk'],
            "weeks_of_supply": row['weeks_of_supply'],
            "avg_weekly_demand": round(row['avg_demand'], 0),
            "current_inventory": int(row['last_inventory']),
            "action": (
                "Reorder immediately" if row['risk'] == 'HIGH'
                else "Monitor closely" if row['risk'] == 'MEDIUM'
                else "Stock adequate"
            )
        })
    
    return {
        "tool": "get_stockout_risk",
        "warehouse_filter": warehouse or "All warehouses",
        "total_results": len(items),
        "results": items,
        "summary": f"{len([i for i in items if i['risk_level']=='HIGH'])} HIGH risk SKUs found"
    }


# ─────────────────────────────────────────
# TOOL 2 — get_sku_forecast
# ─────────────────────────────────────────

@app.get("/tools/get_sku_forecast")
def get_sku_forecast(sku_id: str, warehouse: str):
    """
    Returns detailed forecast for one specific SKU in one warehouse.
    Planners use this when they want to drill into one product.
    """
    
    # Find this specific SKU in this warehouse
    result = summary[
        (summary['sku_id'].str.lower() == sku_id.lower()) &
        (summary['warehouse'].str.lower() == warehouse.lower())
    ]
    
    # If not found return clear error
    if result.empty:
        raise HTTPException(
            status_code=404,
            detail=f"SKU '{sku_id}' in '{warehouse}' not found"
        )
    
    row = result.iloc[0]
    
    # Get recent sales history for this SKU
    history = df[
        (df['sku_id'].str.lower() == sku_id.lower()) &
        (df['warehouse'].str.lower() == warehouse.lower())
    ].tail(8)
    
    # Simple 4 week forecast based on recent average
    recent_avg = history['demand'].mean()
    forecasts = []
    for week in range(1, 5):
        forecasts.append({
            "week": week,
            "forecast_demand": int(recent_avg),
            "risk": row['risk']
        })
    
    return {
        "tool": "get_sku_forecast",
        "sku_id": sku_id,
        "warehouse": warehouse,
        "current_inventory": int(row['last_inventory']),
        "avg_weekly_demand": round(row['avg_demand'], 1),
        "weeks_of_supply": row['weeks_of_supply'],
        "risk_level": row['risk'],
        "four_week_forecast": forecasts,
        "recommendation": (
            f"Current inventory of {int(row['last_inventory'])} units "
            f"covers {row['weeks_of_supply']} weeks of demand. "
            + (
                "Reorder immediately." if row['risk'] == 'HIGH'
                else "Monitor stock levels." if row['risk'] == 'MEDIUM'
                else "Stock levels adequate."
            )
        )
    }



# ─────────────────────────────────────────
# TOOL 3 — get_sales_history
# ─────────────────────────────────────────

@app.get("/tools/get_sales_history")
def get_sales_history(
    sku_id: str,
    warehouse: str,
    last_n_weeks: int = 12
):
    """
    Returns recent sales history for one SKU in one warehouse.
    Claude uses this to explain WHY a forecast looks the way it does.
    """
    
    # Filter to this SKU and warehouse
    history = df[
        (df['sku_id'].str.lower() == sku_id.lower()) &
        (df['warehouse'].str.lower() == warehouse.lower())
    ].tail(last_n_weeks)
    
    # If not found return error
    if history.empty:
        raise HTTPException(
            status_code=404,
            detail=f"No history found for '{sku_id}' in '{warehouse}'"
        )
    
    # Calculate summary stats from history
    avg_demand  = round(history['demand'].mean(), 1)
    max_demand  = int(history['demand'].max())
    min_demand  = int(history['demand'].min())
    promo_weeks = int(history['is_promo'].sum())
    
    # Check trend — is demand going up or down?
    first_half  = history['demand'].iloc[:last_n_weeks//2].mean()
    second_half = history['demand'].iloc[last_n_weeks//2:].mean()
    
    if second_half > first_half * 1.05:
        trend = "increasing"
    elif second_half < first_half * 0.95:
        trend = "decreasing"
    else:
        trend = "stable"
    
    # Build weekly data list
    weekly = []
    for _, row in history.iterrows():
        weekly.append({
            "date": str(row['date'])[:10],
            "demand": int(row['demand']),
            "inventory": int(row['inventory']),
            "promo_week": bool(row['is_promo'])
        })
    
    return {
        "tool": "get_sales_history",
        "sku_id": sku_id,
        "warehouse": warehouse,
        "weeks_of_history": last_n_weeks,
        "average_weekly_demand": avg_demand,
        "max_weekly_demand": max_demand,
        "min_weekly_demand": min_demand,
        "promo_weeks_in_period": promo_weeks,
        "demand_trend": trend,
        "weekly_data": weekly
    }



# ─────────────────────────────────────────
# TOOL 4 — get_warehouse_summary
# ─────────────────────────────────────────

@app.get("/tools/get_warehouse_summary")
def get_warehouse_summary(warehouse: str):
    """
    Returns overall health summary for one warehouse.
    Claude uses this to answer 'how is Atlanta doing this week?'
    """
    
    # Filter to this warehouse
    wh_data = summary[
        summary['warehouse'].str.lower() == warehouse.lower()
    ]
    
    # If not found return error
    if wh_data.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Warehouse '{warehouse}' not found. Available: Atlanta, Chicago, Dallas, Newark"
        )
    
    # Count risk levels
    high   = len(wh_data[wh_data['risk'] == 'HIGH'])
    medium = len(wh_data[wh_data['risk'] == 'MEDIUM'])
    low    = len(wh_data[wh_data['risk'] == 'LOW'])
    total  = len(wh_data)
    
    # Health score — percentage of SKUs at LOW risk
    health_score = round((low / total) * 100, 1)
    
    # Top 3 most urgent SKUs
    top_risks = wh_data.sort_values(
        'weeks_of_supply', ascending=True
    ).head(3)[['sku_id','weeks_of_supply','risk']].to_dict('records')
    
    # Overall status
    if high > 0:
        status = "ATTENTION NEEDED"
    elif medium > total * 0.5:
        status = "MONITOR CLOSELY"
    else:
        status = "HEALTHY"
    
    return {
        "tool": "get_warehouse_summary",
        "warehouse": warehouse,
        "overall_status": status,
        "health_score": health_score,
        "total_skus": total,
        "risk_breakdown": {
            "HIGH": high,
            "MEDIUM": medium,
            "LOW": low
        },
        "top_3_urgent_skus": top_risks,
        "summary": (
            f"{warehouse} warehouse has {high} HIGH risk, "
            f"{medium} MEDIUM risk, and {low} LOW risk SKUs. "
            f"Overall health score: {health_score}%. "
            f"Status: {status}."
        )
    }


# ─────────────────────────────────────────
# HEALTH CHECK
# ─────────────────────────────────────────

@app.get("/")
def health_check():
    """
    Simple health check — confirms server is running.
    """
    return {
        "server": "SBD Demand Forecast MCP Server",
        "status": "running",
        "tools_available": [
            "GET /tools/get_stockout_risk",
            "GET /tools/get_sku_forecast",
            "GET /tools/get_sales_history",
            "GET /tools/get_warehouse_summary"
        ],
        "data_loaded": {
            "total_skus": df['sku_id'].nunique(),
            "warehouses": df['warehouse'].unique().tolist(),
            "total_combinations": len(summary)
        }
    }